### ISSUE TITLE
Error 404 File not found

### ISSUE THREAD

**Issue by ghost** [TheLillo/generate-image-hc4-armbian#1]
while executing the script, it stops with the Error 404 File not found.
maybe the script doesn't find the armbian-source?

Terminal output:
_umount: /mnt: nicht eingehängt.
umount: /tmp/odroid: kein Einhängepunkt angegeben.
--2022-09-12 09:00:01--  https://redirect.armbian.com/region/EU/odroidhc4/Jammy_edge
Auflösen des Hostnamens redirect.armbian.com (redirect.armbian.com) … 107.175.134.226
Verbindungsaufbau zu redirect.armbian.com (redirect.armbian.com)|107.175.134.226|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 302 Found
Platz: https://fi.mirror.armbian.de/dl/odroidhc4/Jammy_edge [folgend]
--2022-09-12 09:00:02--  https://fi.mirror.armbian.de/dl/odroidhc4/Jammy_edge
Auflösen des Hostnamens fi.mirror.armbian.de (fi.mirror.armbian.de) … 135.181.0.235, 2a01:4f9:4b:4db0::2
Verbindungsaufbau zu fi.mirror.armbian.de (fi.mirror.armbian.de)|135.181.0.235|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2022-09-12 09:00:02 FEHLER 404: Not Found._

**Comment by berdav** [comment]
Hi, armbian remove the Jammy_edge version, I've migrated to Jammy_current, can you confirm that it is working now with the current main branch?

**Comment by samxx92** [comment]
Hi, i tried it some days ago (i edited the script) and it worked well with both jammy current and bullseye.

**Comment by berdav** [comment]
Nice, thank you, closing the issue.  I will reopen it if the script has more problems or you can open another one.
