### ISSUE TITLE
Download locations have changed in Armbian 23.11; script fails to download

### ISSUE THREAD

**Issue by emk2203** [TheLillo/generate-image-hc4-armbian#3]
Just when I got around to try it, I noticed that since 23.11, the paths have changed and the script can't download.

Could you please look into it? Thanks in advance!

As a quick fix for anyone else, download the latest Jammy version for the HC4 from Armbian, put them in the `generate-image-hc4-armbian-main` directory and rename to `Jammy_current.xz`.

In the `generate-image.sh` script, comment out lines 24, 29, 30 and 32 and run it.

**Comment by TheLillo** [comment]
Hi @emk2203,

I fixed the way the script gets the Armibian image
